# Tomcat settings
server:
  port: ${TOMCAT_SERVER_PORT:9090}

# Management settings
management:
  endpoints:
    web:
      exposure:
        #include: health,info
        include: "*"

# Spring settings
spring:
  profiles:
    active: dev
  application:
    name: api-order-server
  cloud:
    consul:
      host: 10.0.11.21
      port: 8500
      discovery:
        #register: false
        instance-id: ${spring.application.name}_${spring.cloud.client.ip-address}_${server.port}
        tags: app=order, version=0.0.3-SNAPSHOT
        healthCheckPath: ${management.context-path}/health
        healthCheckInterval: 15s
        prefer-ip-address: true

# Logging settings
logging:
  level:
    root: WARN
    org:
      springframework:
        security: INFO
        web: ERROR
      hibernate: INFO
    com:
      incarcloud: DEBUG
  file:
    path: ${LOGGING_FILE_PATH:./}
    name: order.log
    max-size: ${LOGGING_FILE_MAX_SIZE:20MB}
